# Generated by Django 2.0.2 on 2018-03-04 21:54

import album.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='앨범명')),
                ('img_cover', models.ImageField(blank=True, upload_to=album.models.dynamic_album_cover_path, verbose_name='커버 이미지')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='발매일')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user_info_list', to='album.Album')),
            ],
        ),
    ]
