# Generated by Django 2.0.2 on 2018-02-23 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
