# Generated by Django 2.0.2 on 2018-03-04 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
        ('artist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='곡 제목')),
                ('genre', models.CharField(max_length=100, verbose_name='장르')),
                ('lyrics', models.TextField(blank=True, verbose_name='가사')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Album', verbose_name='앨범')),
                ('artists', models.ManyToManyField(blank=True, to='artist.Artist', verbose_name='아티스트 목록')),
            ],
        ),
        migrations.CreateModel(
            name='SongLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user_info_list', to='song.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_song_info_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_songs', through='song.SongLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='songlike',
            unique_together={('song', 'user')},
        ),
    ]
