# Generated by Django 2.0.2 on 2018-02-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0012_auto_20180221_1429'),
        ('song', '0013_song_song_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(blank=True, to='artist.Artist', verbose_name='아티스트 목록'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, verbose_name='가사'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=100, verbose_name='곡 제목'),
        ),
    ]
