# Generated by Django 2.0.2 on 2018-02-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=30, unique=True, verbose_name='YouTube VideoId')),
                ('title', models.CharField(max_length=100, verbose_name='Video title')),
                ('thumbnail', models.ImageField(blank=True, upload_to='video', verbose_name='Thumbnail image')),
            ],
        ),
    ]
