# Generated by Django 2.0.2 on 2018-02-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='YouTube VideoId'),
        ),
    ]
