# Generated by Django 2.0.2 on 2018-02-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
        ('artist', '0004_auto_20180226_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='videos',
            field=models.ManyToManyField(to='video.Video'),
        ),
    ]
